141,1
V,montestalk,4
V,hds,4
A,FldFun,13,pBasis,Discriminant,FactorizedDiscriminant,FactorizedPrimes,IntegralBasis,LocalIndex,pHermiteBasis,PrimeIdeals,TreesIntervals,localbasedata,maxorderfinite,Times,SFLCount
S,Deg,,0,1,0,0,0,0,0,0,0,5,,148,-38,-38,-38,-38
S,Deg,"Let f=g/h with (g,h)=1. Then Degree(f)=Degree(g)-Degree(h)",0,1,0,0,0,0,0,0,0,238,,148,-38,-38,-38,-38
S,Sort2,Helpmethod for Sort,0,1,0,0,0,0,0,0,0,168,,168,-38,-38,-38,-38
S,DefiningMonicPolynomial,,0,1,0,0,0,0,0,0,0,4,,4,-38,-38,-38,-38
S,InfinityRepresentation,"Input: Function field F with indeterminate T, outpout: Function field F with indeterminate 1/T",0,1,0,0,0,0,0,0,0,4,,4,-38,-38,-38,-38
S,TranslationMap,"Input: z element of function field F with indeterminate T, output: z element of isomorphic function field F` with indeterminate 1/T",0,2,0,0,0,0,0,0,0,4,,0,0,5,,5,-38,-38,-38,-38
S,Montes,,0,2,0,0,1,0,0,0,0,312,,0,0,4,,-38,-38,-38,-38,-38
S,Montesloop,,0,5,0,0,1,0,0,1,1,-38,,1,1,-38,,1,1,-38,,1,1,-38,,0,0,-1,,-38,-38,-38,-38,-38
S,IsPrimeIdeal,True iff I is a record of type IdealRecord or PrimeIdealRecord corresponding to a prime ideal,0,1,0,0,0,0,0,0,0,270,,36,-38,-38,-38,-38
S,IsIdealRecord,True iff I is a record of type IdealRecord,0,1,0,0,0,0,0,0,0,270,,36,-38,-38,-38,-38
S,IsPrimeIdealRecord,True iff I is a record of type PrimeIdealRecord,0,1,0,0,0,0,0,0,0,270,,36,-38,-38,-38,-38
S,ideal,Define the fractional ideal generated by the elements of listgen,1,1,1,82,0,5,2,0,0,0,0,0,0,0,82,,0,0,4,,270,-38,-38,-38,-38
S,ideal,Define the principal fractional ideal generated by a,0,2,0,0,0,0,0,0,0,5,,0,0,4,,270,-38,-38,-38,-38
S,ideal,Define the principal fractional ideal generated by the integer a,0,2,0,0,0,0,0,0,0,312,,0,0,4,,270,-38,-38,-38,-38
S,SumListToString,Technical function to write down a factorization in a pretty form. For internal use only,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,298,-38,-38,-38,-38
S,PValuation,"Compute the P-valuation of alpha at the prime ideal P, which can be given either as PrimeIdealRecord or as an IdealRecord",0,2,0,0,0,0,0,0,0,270,,0,0,5,,148,85,-38,-38,-38
S,PValuation,"Compute the P-valuation of alpha at the prime ideal P, which can be given either as PrimeIdealRecord or as an IdealRecord",0,2,0,0,0,0,0,0,0,270,,0,0,312,,148,85,-38,-38,-38
S,PValuation,"Compute the P-valuation of alpha at the prime ideal P, which can be given either as PrimeIdealRecord or as an IdealRecord. Also the class of alpha in P^value/P^value+1",0,2,0,0,0,0,0,0,0,270,,0,0,5,,148,85,-38,-38,-38
S,InitialLevel,psi is a monic irreducible factor of Pol modulo p and power=ord_psi(Pol mod p),0,5,0,0,0,0,0,0,0,-1,,0,0,-1,,0,0,-1,,0,0,-1,,0,0,-1,,270,-38,-38,-38,-38
S,PrescribedValue,"if type is attached to the prime ideal P with Okutsu depth r, then logpsi=[a_0,...,a_r] and Psi=phi_1^a_1...phi_r^a_r, with v_P(p^a_0Psi(theta))=value",0,4,0,0,1,0,0,1,1,-38,,1,1,-38,,0,0,-1,,1,1,-38,,-38,-38,-38,-38,-38
S,CrossedValues,Rows of Mat indexed by phi_Q and columns by w_P:=v_P/e(P/p),0,2,0,0,1,0,0,0,0,-1,,1,1,-38,,-38,-38,-38,-38,-38
S,Taylor,Compute the first omega+1 coefficients of the phi-expansion of pol,0,3,0,0,0,0,0,0,0,148,,0,0,312,,0,0,312,,82,-38,-38,-38,-38
S,Newton,"Given a type of order at least r, and a polynomial, compute the list of sides of the r-th order Newton polygon w.r.t. the type",0,3,0,0,0,0,0,0,0,-1,,0,0,-1,,0,0,-1,,82,-38,-38,-38,-38
S,OkutsuBasis,Computes Okutsu basis of P,0,1,0,0,1,0,0,1,1,270,,-38,-38,-38,-38,-38
S,LastLevel,in type[1]`sfl[1] we store the exponent of the irreducible factor,0,4,0,0,1,0,0,0,0,-1,,0,0,-1,,1,1,-38,,0,0,-1,,-38,-38,-38,-38,-38
S,ResidualPolynomial,Internal procedure to compute the i-th residual polynomial psi with respect to a side S of slope -type[i]`slope of the Newton polygon of a certain polynomial Pol. The coefficients of Pol whose attached points in N_i(Pol) lie on S have multiadic expansions contained in the list devsSide,0,4,0,0,1,0,0,1,1,-38,,1,1,-38,,1,1,-38,,0,0,-1,,-38,-38,-38,-38,-38
S,Localize,"output=den,exp,Pol such that alpha = (1/den)*Pol(theta)*p^exp, and den is coprime to p",0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,148,148,312,-38,-38
S,VValuation,,0,2,0,0,0,0,0,0,0,312,,0,0,312,,148,-38,-38,-38,-38
S,ConvertLogs,log[1] is not used. The product of all Phi_i^log[i] for i>0 should have integer value M. The output is the class of this product divided by p^M,0,3,0,0,1,0,0,1,1,-38,,0,0,-1,,1,1,-38,,-38,-38,-38,-38,-38
S,SFL,in type[1]`sfl and type[1]`Phiadic we stored relevant data. The aim is type[#type]`slope>=slope,0,2,0,0,1,0,0,0,0,148,,1,1,82,,-38,-38,-38,-38,-38
S,InitialeModRing,,0,2,0,0,0,0,0,0,0,312,,0,0,311,,311,-38,-38,-38,-38
S,PutModRing,,0,2,0,0,0,0,0,0,0,312,,0,0,311,,311,-38,-38,-38,-38
S,ChangePrecMod,,0,2,0,0,0,0,0,0,0,312,,0,0,311,,311,-38,-38,-38,-38
S,SFL,,0,3,0,0,1,0,0,0,0,148,,1,1,270,,1,1,4,,-38,-38,-38,-38,-38
S,SFLInitialize,,0,1,0,0,1,0,0,1,1,-38,,-38,-38,-38,-38,-38
S,Value,"Given a level i, a type and a polynomial pol, the output is: devs=multiexpansion with respect to phi_1,...,phi_i-1 of the points in S_lambda_i-1(pol) val=i-th valuation of pol w.r.t. type",0,5,0,0,1,0,0,1,1,-38,,1,1,-38,,0,0,-1,,1,1,-38,,0,0,-1,,-38,-38,-38,-38,-38
S,EqualizeLogs,,0,2,0,0,1,0,0,1,1,-38,,1,1,-38,,-38,-38,-38,-38,-38
S,Z,z=z_i belongs to F_(i+1),0,3,0,0,1,0,0,1,1,-38,,0,0,-1,,1,1,-38,,-38,-38,-38,-38,-38
S,IndexOfCoincidence,the types must correspond to different prime ideals,0,3,0,0,1,0,0,1,1,-38,,1,1,-38,,1,1,-38,,-38,-38,-38,-38,-38
S,IndexOfCoincidence,The index of coincidence of types t1 and t2,0,2,0,0,0,0,0,0,0,270,,0,0,270,,148,-38,-38,-38,-38
S,IndexOfCoincidence,,0,2,0,0,0,0,0,0,0,82,,0,0,82,,148,-38,-38,-38,-38
S,PathOfPrecisions,,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,82,-38,-38,-38,-38
S,reduce,,0,3,0,0,0,0,0,0,0,-1,,0,0,-1,,0,0,-1,,312,148,-38,-38,-38
S,Inversionloop,,0,6,0,0,1,0,0,0,0,-1,,0,0,-1,,1,1,-38,,1,1,-38,,0,0,-1,,0,0,-1,,-38,-38,-38,-38,-38
S,UpdateLastLevel,,0,1,0,0,1,0,0,1,1,-38,,-38,-38,-38,-38,-38
S,LocalLift,"class should belong to the residue class field type[r]`Fq. The output is a pair g,e such that g(theta)/p^e is a lift to a P-integral element in K and deg g(x)<n_P",0,4,0,0,1,0,0,1,1,-38,,1,1,-38,,0,0,-1,,1,1,-38,,-38,-38,-38,-38,-38
S,LocalLift,class should belong to the residue class field Z_K/P. The output is a lift to a P-integral element in K,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,5,-38,-38,-38,-38
S,Construct,"This routine constructs a polynomial Ppol with integer coefficients such that: deg Ppol<m_i+1 and y^nu*R_i(Ppol)(y)=respol(y), where nu=ord_y(respol). The non-negative integers s,u are the coordinates of the left endpoint of a segment of slope -type[i]`slope supporting N_i(Ppol)",0,6,0,0,1,0,0,1,1,-38,,0,0,-1,,0,0,-1,,0,0,-1,,1,1,-38,,0,0,-1,,-38,-38,-38,-38,-38
S,Newton,"Given a type of order at least i, and the phiadic expansion of a polynomial, compute: sides=list of sides of the r-th order Newton polygon w.r.t. the type, and devsEachSide[k]=list of multiadic phi_1,...,phi_i-1 expansion of the coefficients of the polynomial whose attached point lies on sides[k]",0,5,0,0,1,0,0,1,1,-38,,1,1,-38,,1,1,-38,,1,1,-38,,0,0,-1,,-38,-38,-38,-38,-38
S,*,"Compute the product of the fractional ideals I,J. They are both factored if their factorization is not yet known",0,2,0,0,0,0,0,0,0,270,,0,0,270,,270,-38,-38,-38,-38
S,^,Compute the n-th power of the fractional ideal I. The ideal I is factored if it is not already known its factorization,0,2,0,0,0,0,0,0,0,148,,0,0,270,,270,-38,-38,-38,-38
S,FactorListToString,Technical function to write down a factorization in pretty form. For internal use only,0,1,0,0,0,0,0,0,0,-1,,298,-38,-38,-38,-38
S,IsZero,True iff I is the zero ideal,0,1,0,0,0,0,0,0,0,270,,36,-38,-38,-38,-38
S,Factorization,Compute the decomposition of the fractional ideal I into prime ideals,0,1,0,0,0,0,0,0,0,270,,82,-38,-38,-38,-38
S,Factorization,Compute the decomposition of the fractional ideal I into prime ideals,0,1,0,0,1,0,0,1,1,270,,-38,-38,-38,-38,-38
S,Representative,Construction of a representative phi of a type. We add phi and V at a new level of type,0,1,0,0,1,0,0,1,1,-38,,-38,-38,-38,-38,-38
S,ResidualPolynomial,Internal procedure to compute the i-th residual polynomial psi with respect to a side S of slope -type[i]`slope of the Newton polygon of a certain polynomial Pol. The coefficients of Pol whose attached points in N_i(Pol) lie on S have multiadic expansions contained in the list devsSide,0,4,0,0,1,0,0,1,1,-38,,1,1,-38,,1,1,-38,,0,0,-1,,-38,-38,-38,-38,-38
S,Inverse,Speeds up inversion of a matrix over the rational function field,0,2,0,0,0,0,0,0,0,238,,0,0,177,,177,-38,-38,-38,-38
S,Ideal_Basis,Computes a Hermite basis of the ideal I,0,1,0,0,0,0,0,0,0,270,,82,-38,-38,-38,-38
S,pBasis,Computes a p-integral basis of the fractional ideal in Hermite Form or if Reduced is set true an p-orthonormal basis of I,0,2,0,0,0,0,0,0,0,312,,0,0,270,,82,-38,-38,-38,-38
S,pBasisMultiplier,Computes a p-integral basis of the fractional ideal in Hermite Form or if Reduced is set true an p-orthonormal basis of I,0,2,0,0,0,0,0,0,0,312,,0,0,270,,82,-38,-38,-38,-38
S,Index,Computes the index of the maximal order O_K over the equation order of K and factorizes the discriminant of K,0,1,0,0,0,0,0,0,0,4,,82,-38,-38,-38,-38
S,pBasisRed,Computes a p-integral basis of the fractional ideal in Hermite Form or if Reduced is set true an p-orthonormal basis of I,0,2,0,0,0,0,0,0,0,312,,0,0,270,,82,-38,-38,-38,-38
S,Multipliers,Computes computes Multiplier,0,6,0,0,0,0,0,0,0,36,,0,0,82,,0,0,82,,0,0,82,,0,0,312,,0,0,4,,82,-38,-38,-38,-38
S,ReductionAlgorithm,"Let the rows of T be a lattice L in K^n, Output: T, whose rows form a reduced basis of L",0,1,0,0,0,0,0,0,0,177,,177,-38,-38,-38,-38
S,SIdeal_Basis,Compute a local integral basis of I for the given set of primes,0,2,0,0,0,0,0,0,0,82,,0,0,270,,82,-38,-38,-38,-38
S,RationalRadical,Compute the rational prime numbers dividing the norm of the ideal I,0,1,0,0,0,0,0,0,0,270,,82,-38,-38,-38,-38
S,PhiExpo,Compute mi/m_i-1 representation of an integer m,0,2,0,0,0,0,0,0,0,82,,0,0,148,,82,-38,-38,-38,-38
S,PhiValuation,Computes the valuation of Phi at Prime,0,4,0,0,0,0,0,0,0,148,,0,0,82,,0,0,312,,0,0,4,,148,-38,-38,-38,-38
S,ComputeMultiplierShort,Determines Multipliers,0,6,0,0,0,0,0,0,0,82,,0,0,82,,0,0,82,,0,0,82,,0,0,312,,0,0,4,,82,-38,-38,-38,-38
S,ProdList,Produces [p^[Expos[i]]:i in [1..#Expos]] in a intelligent way,0,2,0,0,0,0,0,0,0,312,,0,0,82,,82,-38,-38,-38,-38
S,MultiplierH,Computes Multiplier,0,6,0,0,0,0,0,0,0,36,,0,0,82,,0,0,82,,0,0,82,,0,0,82,,0,0,168,,82,-38,-38,-38,-38
S,Subsec,Splits Liste into sublists of length Lenght[i],0,3,0,0,0,0,0,0,0,82,,0,0,312,,0,0,82,,82,-38,-38,-38,-38
S,Equal,,0,2,0,0,0,0,0,0,0,168,,0,0,168,,36,-38,-38,-38,-38
S,eq,"True iff the fractional ideals I,J are equal. They are both factored if their factorization is not yet kwown",0,2,0,0,0,0,0,0,0,270,,0,0,270,,36,-38,-38,-38,-38
S,Truncate,,0,1,0,0,1,0,0,1,1,-38,,-38,-38,-38,-38,-38
S,CRT,Compute x congruent to elements[j] mod ideals[j] for every j. Integrality of the given elements is not checked!,2,0,1,82,0,5,1,1,82,0,270,2,0,0,0,0,0,0,0,82,,0,0,82,,5,-38,-38,-38,-38
S,LocalCRT,,0,4,0,0,1,0,0,1,1,-38,,0,0,-1,,0,0,-1,,1,1,-38,,-38,-38,-38,-38,-38
S,MultPiece,"output bp has P-value zero and v_Q(bp) >= expsTree[Q]+extraden*e_Q, for all Qne P in the tree",0,5,0,0,1,0,0,1,1,-38,,1,1,-38,,0,0,-1,,0,0,-1,,1,1,-38,,-38,-38,-38,-38,-38
S,CompensateValue,"tree is an interval [i..j] inside [1..#K`PrimeIdeals[p]] and exponents is a sequence of integers of length #tree. The output is a power of the greatest common phi-polynomial of the tree, such that v_P >= exponents[P] for all P in the tree",0,5,0,0,1,0,0,1,1,-38,,0,0,-1,,0,0,-1,,0,0,-1,,1,1,-38,,-38,-38,-38,-38,-38
S,MultiplyByInverse,"alpha is divided by an inverse, called x, so that the output is congruent to 1 modulo P^m",0,3,0,0,1,0,0,0,0,-1,,1,1,-38,,1,1,-38,,-38,-38,-38,-38,-38
S,GCPhi,the output phi is the greatest common phi-polynomial of the tree. Values is the sequence of all v_P(phi(theta)) for P in the tree. node is the level of phi,0,6,0,0,1,0,0,1,1,-38,,1,1,-38,,1,1,-38,,0,0,-1,,0,0,-1,,1,1,-38,,-38,-38,-38,-38,-38
S,Reduction,reduction map ZK--> ZK/P^m,0,3,0,0,0,0,0,0,0,148,,0,0,270,,0,0,5,,82,-38,-38,-38,-38
S,Simplify,"beta is P-integral. The output is congruent to beta mod P^m and it has: denominator=p^power, deg(numerator) less than n_P, and numerator simplified mod p^power+(m/eP)",0,3,0,0,1,0,0,0,0,-1,,1,1,-38,,1,1,-38,,-38,-38,-38,-38,-38
S,PadicDevelopment,Berechnet pi entwicklung von v_P(alpha) bis l,0,3,0,0,0,0,0,0,0,270,,0,0,148,,0,0,5,,82,-38,-38,-38,-38
S,Random_FunctionField,produces more or less random function field of degree deg over finite field with 	q elements - coefficients of f are bounded by B,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,4,-38,-38,-38,-38
